//
//  SignInInteractorTests.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import NurseHelper
import XCTest

class SignInInteractorTests: XCTestCase {
  // MARK: - Subject under test
  
  var sut: SignInInteractor!
  
  // MARK: - Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupSignInInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupSignInInteractor() {
    sut = SignInInteractor()
  }
  
  // MARK: - Test doubles
  
  class SignInInteractorOutputSpy : SignInInteractorOutput {
    var presentErrorMessageWasCalled = false
    var presentPageAfterLoginWasCalled = false
    
    func presentErrorMessage(response: SignIn.Response) {
      presentErrorMessageWasCalled = true
    }
    
    func presentPageAfterLogin() {
      presentPageAfterLoginWasCalled = true
    }
  }
  
  // MARK: - Tests
  
}
