//
//  SignInWorkerTests.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import NurseHelper
import XCTest

class SignInWorkerTests: XCTestCase {
  // MARK: - Subject under test
  
  var sut: SignInWorker!
  
  // MARK: - Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupSignInWorker()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupSignInWorker() {
    sut = SignInWorker()
  }
  
  // MARK: - Test doubles
  
  // MARK: - Tests
  
  func testSomething() {
    // Given
    
    // When
    
    // Then
  }
}
