//
//  SignInViewControllerTests.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import NurseHelper
import XCTest

class SignInViewControllerTests: XCTestCase {
  // MARK: - Subject under test
  
  var sut: SignInViewController!
  var window: UIWindow!
  
  // MARK: - Test lifecycle
  
  override func setUp() {
    super.setUp()
    window = UIWindow()
    setupSignInViewController()
  }
  
  override func tearDown() {
    window = nil
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupSignInViewController() {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "Login", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "SignInViewController") as! SignInViewController
    loadView()
  }
  
  func loadView() {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: - Test doubles
  
  class OutputSpy : SignInViewControllerOutput {
    var request:SignIn.Request!
    var signInWasCalled = false
    func signIn(request: SignIn.Request) {
        signInWasCalled = true
        self.request = request
    }
  }
  
  // MARK: - Tests
  
  func testThatSignInCalledInOutput() {
   
    let spy = OutputSpy()
    sut.output = spy
    sut.signIn(self)
    
    XCTAssertTrue(spy.signInWasCalled)
  }
  
  func testThatSignInSendProperParameters() {
    let spy = OutputSpy()
    sut.output = spy

    sut.emailField.text = "proper@mail.com"
    sut.passwordField.text = "123456"
    
    sut.signIn(self)
    
    XCTAssert(spy.request.email == "proper@mail.com")
    XCTAssert(spy.request.password == "123456")
  }
}
