//
//  SignInWorker.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

typealias SignInWorkerCompletion = (_ result:Bool, _ message:String) -> Void

protocol SignInWorkerDataSource {
  func signIn(withEmail:String,password:String,completion: @escaping SignInWorkerCompletion)
}

class SignInWorker {
  var dataSource:SignInWorkerDataSource?
  var emailValidator:StringValidator!
  var passwordValidator:StringValidator!
  
  func login(email:String, password:String, completion:@escaping SignInWorkerCompletion) {
    //TODO - validation
    let emailValidationResult = emailValidator.validate(string: email)
    let passwordValidationResult = passwordValidator.validate(string: email)
    
    switch emailValidationResult {
    case .wrongString(let errors):
      completion(false, "Email has wrong format")
      return
    default:
      break
    }
    
    switch passwordValidationResult {
    case .wrongString(let errors):
      completion(false,"Password has wrong format")
      return
    default:
      break
    }
    
    dataSource?.signIn(withEmail: email, password: password, completion: { (result, message) in
      completion(result,message)
    })
  }
}
