//
//  SignInViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignInViewControllerInput {
  func displayErrorMessage(viewModel: SignIn.ViewModel)
  func displayPageAfterLogin()
}

protocol SignInViewControllerOutput {
  func signIn(request: SignIn.Request)
}

class SignInViewController: UIViewController, SignInViewControllerInput {
  var output: SignInViewControllerOutput!
  var router: SignInRouter!
  
  // MARK: - IBOutlets
  
  @IBOutlet weak var emailField: UITextField!
  @IBOutlet weak var passwordField: UITextField!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    SignInConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  // MARK: - Event handling
  
  @IBAction func signIn(_ sender: Any) {
    let request = SignIn.Request(email:emailField.text ?? "", password: passwordField.text ?? "")
    output.signIn(request: request)
  }
  
  @IBAction func goToSignUp(_ sender: Any) {
      router.navigateToSignUp()
  }
  
  // MARK: - Display logic
  
  func displayErrorMessage(viewModel: SignIn.ViewModel) {
    displayErrorAlert(message: viewModel.resultMessage)
  }
  
  func displayPageAfterLogin() {
    router.navigateToNextPage()
  }
}

private extension SignInViewController {
  func displayErrorAlert(message:String) {
    
  }
}
