//
//  SignInModels.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct SignIn {
    struct Request {
      let email:String
      let password:String
    }
    struct Response {
      let success:Bool
      let resultMessage:String
    }
    struct ViewModel {
      let resultMessage:String
    }
}
