//
//  SignInInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignInInteractorInput {
  func signIn(request: SignIn.Request)
}

protocol SignInInteractorOutput {
  func presentErrorMessage(response: SignIn.Response)
  func presentPageAfterLogin()
}

class SignInInteractor: SignInInteractorInput {
  var output: SignInInteractorOutput!
  var worker: SignInWorker!
  
  // MARK: - Business logic
  
    func signIn(request: SignIn.Request) {
        worker = SignInWorker()
      
        worker.dataSource = SignInManagerImpl()
        worker.emailValidator = EmailValidator()
        worker.passwordValidator = PasswordValidator()
      
        worker.login(email: request.email, password: request.password) { (result, message) in
          if result {
            self.output.presentPageAfterLogin()
          }
          else {
            let response = SignIn.Response(success: false, resultMessage: message)
            self.output.presentErrorMessage(response: response)
          }
        }
     
    }
}

extension SignInManagerImpl : SignInWorkerDataSource {
  
}
