//
//  SignInPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignInPresenterInput {
  func presentErrorMessage(response: SignIn.Response)
  func presentPageAfterLogin()
}

protocol SignInPresenterOutput: class {
  func displayErrorMessage(viewModel: SignIn.ViewModel)
  func displayPageAfterLogin()
}

class SignInPresenter: SignInPresenterInput
{
  weak var output: SignInPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentErrorMessage(response: SignIn.Response) {
    let viewModel = SignIn.ViewModel(resultMessage: response.resultMessage)
    output.displayErrorMessage(viewModel: viewModel)
  }
  
  func presentPageAfterLogin() {
    output.displayPageAfterLogin()
  }
}
