//
//  AddMedicineConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension AddMedicineViewController: AddMedicinePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension AddMedicineInteractor: AddMedicineViewControllerOutput
{
}

extension AddMedicinePresenter: AddMedicineInteractorOutput
{
}

class AddMedicineConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = AddMedicineConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: AddMedicineViewController)
  {
    let router = AddMedicineRouter()
    router.viewController = viewController
    
    let presenter = AddMedicinePresenter()
    presenter.output = viewController
    
    let interactor = AddMedicineInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
