//
//  AddMedicineViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddMedicineViewControllerInput {
}

protocol AddMedicineViewControllerOutput {
  func addNewMedicine(request:AddMedicine.Request)
}

class AddMedicineViewController: UIViewController, AddMedicineViewControllerInput {
  var output: AddMedicineViewControllerOutput!
  var router: AddMedicineRouter!
  
  //MARK: - IBOutlets
  
  @IBOutlet weak var nameField: UITextField!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    AddMedicineConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  // MARK: - Event handling
  
  @IBAction func addNewMedicine(_ sender: Any) {
    let request = AddMedicine.Request(medicineName: nameField.text ?? "")
    output.addNewMedicine(request: request)
  }
  
  // MARK: - Display logic
  
  func displayErrorMessage(errorMessage:String) {
    
  }
  
  func displayMedicineList() {
    router.navigateToMedicineList()
  }
  
}
