//
//  AddMedicineInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddMedicineInteractorInput {
  func addNewMedicine(request:AddMedicine.Request)
}

protocol AddMedicineInteractorOutput {
  func presentErrorMessage(errorMessage:String)
  func presentMedicineList()
}

class AddMedicineInteractor: AddMedicineInteractorInput {
  var output: AddMedicineInteractorOutput!
  var worker: AddMedicineWorker!
  
  // MARK: - Business logic
  
  func addNewMedicine(request:AddMedicine.Request) {
    worker = AddMedicineWorker()
    worker.medicineNameValidator = MedicineNameValidator()
    worker.addMedicine(withName: request.medicineName) { (result, message) in
      if result {
        self.output.presentMedicineList()
      }
      else {
        self.output.presentErrorMessage(errorMessage: message)
      }
    }
  }
  
}
