//
//  PatientsListConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PatientsListViewController: PatientsListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension PatientsListInteractor: PatientsListViewControllerOutput
{
}

extension PatientsListPresenter: PatientsListInteractorOutput
{
}

class PatientsListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = PatientsListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: PatientsListViewController)
  {
    let router = PatientsListRouter()
    router.viewController = viewController
    
    let presenter = PatientsListPresenter()
    presenter.output = viewController
    
    let interactor = PatientsListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
