//
//  PatientsListViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsListViewControllerInput {
  func displayAllPatients(viewModel: PatientsList.ViewModel)
}

protocol PatientsListViewControllerOutput {
  func loadAllPatients(request: PatientsList.Request)
}

class PatientsListViewController: UIViewController, PatientsListViewControllerInput {
  var output: PatientsListViewControllerOutput!
  var router: PatientsListRouter!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    PatientsListConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  // MARK: - Event handling

  
  // MARK: - Display logic
  
  func displayAllPatients(viewModel: PatientsList.ViewModel) {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
