//
//  PatientsListInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsListInteractorInput {
  func loadAllPatients(request: PatientsList.Request)
}

protocol PatientsListInteractorOutput {
  func presentAllPatients(response: PatientsList.Response)
}

class PatientsListInteractor: PatientsListInteractorInput {
  var output: PatientsListInteractorOutput!
  var worker: PatientsListWorker!
  
  // MARK: - Business logic
  func loadAllPatients(request: PatientsList.Request) {
    
  }

}
