//
//  SignUpViewControllerTests.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/31/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import NurseHelper
import XCTest

class SignUpViewControllerTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: SignUpViewController!
  var window: UIWindow!
  
  // MARK: - Test lifecycle
  
  override func setUp() {
    super.setUp()
    window = UIWindow()
    setupSignUpViewController()
  }
  
  override func tearDown() {
    window = nil
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupSignUpViewController() {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "Login", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "SignUpViewController") as! SignUpViewController
  }
  
  func loadView() {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: - Test doubles
    
  class ViewControllerOutputSpy : SignUpViewControllerOutput {
      var signUpWasCalled = false
      var request:SignUp.Request!
        
      func signUp(request: SignUp.Request) {
          signUpWasCalled = true
          self.request = request
      }

  }
  
  // MARK: - Tests
  
  func testThatIBActionCallsSignupInOutput() {
      loadView()
      let spy = ViewControllerOutputSpy()
      sut.output = spy
        
      sut.signUp(self)
        
      XCTAssertTrue(spy.signUpWasCalled)
  }

  func testThatOutputReceivesCorrectValues() {
      loadView()
      let spy = ViewControllerOutputSpy()
      sut.output = spy
    
      sut.emailField.text = "test@mail.com"
      sut.passwordField.text = "1234567"
    
      sut.signUp(self)
    
      XCTAssertTrue(spy.request.email == "test@mail.com")
      XCTAssertTrue(spy.request.password == "1234567")
  }
}
