//
//  SignUpInteractorTests.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/31/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import NurseHelper
import XCTest

class SignUpInteractorTests: XCTestCase {
  // MARK: - Subject under test
  
  var sut: SignUpInteractor!
  
  // MARK: - Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupSignUpInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupSignUpInteractor() {
    sut = SignUpInteractor()
  }
  
  // MARK: - Test doubles
  
  class OutputSpy : SignUpInteractorOutput {
    var presentErrorMessageWasCalled = false
    var presentPageAfterSignUpWasCalled = false
    var response:SignUp.Response!
    
    func presentErrorMessage(response: SignUp.Response) {
      presentErrorMessageWasCalled = true
      self.response = response
    }
    
    func presentPageAfterSignUp() {
      presentPageAfterSignUpWasCalled = true
    }

  }
  
  // MARK: - Tests
  
}
