//
//  ScheduleSelectPatientPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleSelectPatientPresenterInput
{
  func presentSomething(response: ScheduleSelectPatient.Something.Response)
}

protocol ScheduleSelectPatientPresenterOutput: class
{
  func displaySomething(viewModel: ScheduleSelectPatient.Something.ViewModel)
}

class ScheduleSelectPatientPresenter: ScheduleSelectPatientPresenterInput
{
  weak var output: ScheduleSelectPatientPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ScheduleSelectPatient.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ScheduleSelectPatient.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
