//
//  ScheduleSelectPatientViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleSelectPatientViewControllerInput
{
  func displaySomething(viewModel: ScheduleSelectPatient.Something.ViewModel)
}

protocol ScheduleSelectPatientViewControllerOutput
{
  func doSomething(request: ScheduleSelectPatient.Something.Request)
}

class ScheduleSelectPatientViewController: UIViewController, ScheduleSelectPatientViewControllerInput
{
  var output: ScheduleSelectPatientViewControllerOutput!
  var router: ScheduleSelectPatientRouter!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ScheduleSelectPatientConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: - Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ScheduleSelectPatient.Something.Request()
    output.doSomething(request: request)
  }
  
  // MARK: - Display logic
  
  func displaySomething(viewModel: ScheduleSelectPatient.Something.ViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
