//
//  ScheduleSelectPatientInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleSelectPatientInteractorInput
{
  func doSomething(request: ScheduleSelectPatient.Something.Request)
}

protocol ScheduleSelectPatientInteractorOutput
{
  func presentSomething(response: ScheduleSelectPatient.Something.Response)
}

class ScheduleSelectPatientInteractor: ScheduleSelectPatientInteractorInput
{
  var output: ScheduleSelectPatientInteractorOutput!
  var worker: ScheduleSelectPatientWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: ScheduleSelectPatient.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ScheduleSelectPatientWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ScheduleSelectPatient.Something.Response()
    output.presentSomething(response: response)
  }
}
