//
//  AddScheduleInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddScheduleInteractorInput
{
  func doSomething(request: AddSchedule.Something.Request)
}

protocol AddScheduleInteractorOutput
{
  func presentSomething(response: AddSchedule.Something.Response)
}

class AddScheduleInteractor: AddScheduleInteractorInput
{
  var output: AddScheduleInteractorOutput!
  var worker: AddScheduleWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: AddSchedule.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = AddScheduleWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = AddSchedule.Something.Response()
    output.presentSomething(response: response)
  }
}
