//
//  AddScheduleConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension AddScheduleViewController: AddSchedulePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension AddScheduleInteractor: AddScheduleViewControllerOutput
{
}

extension AddSchedulePresenter: AddScheduleInteractorOutput
{
}

class AddScheduleConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = AddScheduleConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: AddScheduleViewController)
  {
    let router = AddScheduleRouter()
    router.viewController = viewController
    
    let presenter = AddSchedulePresenter()
    presenter.output = viewController
    
    let interactor = AddScheduleInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
