//
//  AddSchedulePresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddSchedulePresenterInput
{
  func presentSomething(response: AddSchedule.Something.Response)
}

protocol AddSchedulePresenterOutput: class
{
  func displaySomething(viewModel: AddSchedule.Something.ViewModel)
}

class AddSchedulePresenter: AddSchedulePresenterInput
{
  weak var output: AddSchedulePresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: AddSchedule.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = AddSchedule.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
