//
//  PatientsTabViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsTabViewControllerInput {
  func displaySomething(viewModel: PatientsTab.Something.ViewModel)
}

protocol PatientsTabViewControllerOutput {
  func doSomething(request: PatientsTab.Something.Request)
}

class PatientsTabViewController: UIViewController, PatientsTabViewControllerInput {
  var output: PatientsTabViewControllerOutput!
  var router: PatientsTabRouter!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    PatientsTabConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  // MARK: - Event handling
  
  @IBAction func showAddNewPatient(_ sender: Any) {
    router.navigateToAddNewPatientScreen()
  }
  // MARK: - Display logic
  
  func displaySomething(viewModel: PatientsTab.Something.ViewModel) {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
