//
//  PatientsTabPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsTabPresenterInput
{
  func presentSomething(response: PatientsTab.Something.Response)
}

protocol PatientsTabPresenterOutput: class
{
  func displaySomething(viewModel: PatientsTab.Something.ViewModel)
}

class PatientsTabPresenter: PatientsTabPresenterInput
{
  weak var output: PatientsTabPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: PatientsTab.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = PatientsTab.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
