//
//  PatientsTabConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PatientsTabViewController: PatientsTabPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension PatientsTabInteractor: PatientsTabViewControllerOutput
{
}

extension PatientsTabPresenter: PatientsTabInteractorOutput
{
}

class PatientsTabConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = PatientsTabConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: PatientsTabViewController)
  {
    let router = PatientsTabRouter()
    router.viewController = viewController
    
    let presenter = PatientsTabPresenter()
    presenter.output = viewController
    
    let interactor = PatientsTabInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
