//
//  PatientsTabInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsTabInteractorInput
{
  func doSomething(request: PatientsTab.Something.Request)
}

protocol PatientsTabInteractorOutput
{
  func presentSomething(response: PatientsTab.Something.Response)
}

class PatientsTabInteractor: PatientsTabInteractorInput
{
  var output: PatientsTabInteractorOutput!
  var worker: PatientsTabWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: PatientsTab.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = PatientsTabWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = PatientsTab.Something.Response()
    output.presentSomething(response: response)
  }
}
