//
//  MedicineDetailsInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MedicineDetailsInteractorInput
{
  func doSomething(request: MedicineDetails.Something.Request)
}

protocol MedicineDetailsInteractorOutput
{
  func presentSomething(response: MedicineDetails.Something.Response)
}

class MedicineDetailsInteractor: MedicineDetailsInteractorInput
{
  var output: MedicineDetailsInteractorOutput!
  var worker: MedicineDetailsWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: MedicineDetails.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = MedicineDetailsWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = MedicineDetails.Something.Response()
    output.presentSomething(response: response)
  }
}
