//
//  MedicineDetailsPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MedicineDetailsPresenterInput
{
  func presentSomething(response: MedicineDetails.Something.Response)
}

protocol MedicineDetailsPresenterOutput: class
{
  func displaySomething(viewModel: MedicineDetails.Something.ViewModel)
}

class MedicineDetailsPresenter: MedicineDetailsPresenterInput
{
  weak var output: MedicineDetailsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: MedicineDetails.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = MedicineDetails.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
