//
//  PatientsDetailsModulePresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsDetailsModulePresenterInput
{
  func presentSomething(response: PatientsDetailsModule.Something.Response)
}

protocol PatientsDetailsModulePresenterOutput: class
{
  func displaySomething(viewModel: PatientsDetailsModule.Something.ViewModel)
}

class PatientsDetailsModulePresenter: PatientsDetailsModulePresenterInput
{
  weak var output: PatientsDetailsModulePresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: PatientsDetailsModule.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = PatientsDetailsModule.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
