//
//  PatientsDetailsModuleInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol PatientsDetailsModuleInteractorInput
{
  func doSomething(request: PatientsDetailsModule.Something.Request)
}

protocol PatientsDetailsModuleInteractorOutput
{
  func presentSomething(response: PatientsDetailsModule.Something.Response)
}

class PatientsDetailsModuleInteractor: PatientsDetailsModuleInteractorInput
{
  var output: PatientsDetailsModuleInteractorOutput!
  var worker: PatientsDetailsModuleWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: PatientsDetailsModule.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = PatientsDetailsModuleWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = PatientsDetailsModule.Something.Response()
    output.presentSomething(response: response)
  }
}
