//
//  PatientsDetailsModuleConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension PatientsDetailsModuleViewController: PatientsDetailsModulePresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension PatientsDetailsModuleInteractor: PatientsDetailsModuleViewControllerOutput
{
}

extension PatientsDetailsModulePresenter: PatientsDetailsModuleInteractorOutput
{
}

class PatientsDetailsModuleConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = PatientsDetailsModuleConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: PatientsDetailsModuleViewController)
  {
    let router = PatientsDetailsModuleRouter()
    router.viewController = viewController
    
    let presenter = PatientsDetailsModulePresenter()
    presenter.output = viewController
    
    let interactor = PatientsDetailsModuleInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
