//
//  SignUpViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignUpViewControllerInput {
  func displayErrorMessage(viewModel: SignUp.ViewModel)
  func displayPageAfterSignUp()
}

protocol SignUpViewControllerOutput {
  func signUp(request: SignUp.Request)
}

class SignUpViewController: UIViewController, SignUpViewControllerInput {
  var output: SignUpViewControllerOutput!
  var router: SignUpRouter!
  
  //MARK: - IBOutlets
  
  @IBOutlet weak var emailField: UITextField!
  @IBOutlet weak var passwordField: UITextField!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    SignUpConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  // MARK: - Event handling
  
  @IBAction func signUp(_ sender: Any) {
    let request = SignUp.Request(email:emailField.text ?? "",password:passwordField.text ?? "")
    output.signUp(request: request)
  }
  
  @IBAction func goToSignIn(_ sender: Any) {
    router.navigateToSignIn()
  }
  
  // MARK: - Display logic
  
  func displayErrorMessage(viewModel: SignUp.ViewModel) {
    showErrorMessageAlert(message: viewModel.messageToShow)
  }
  
  func displayPageAfterSignUp() {
    router.navigateToNextPageAfterSignUp()
  }
}

private extension SignUpViewController {
  func showErrorMessageAlert(message:String) {
    let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
    
    alert.addAction(UIAlertAction(title: "Dismiss", style: .cancel, handler: { (action) in
      
    }))
    
    present(alert, animated: true, completion: nil)
  }
}
