//
//  SignUpRouter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 1/30/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SignUpRouterInput {
  func navigateToSignIn()
  func navigateToNextPageAfterSignUp()
}

class SignUpRouter: SignUpRouterInput {
  weak var viewController: SignUpViewController!
  
  // MARK: - Navigation
  
  func navigateToSignIn() {
      _ = viewController.navigationController?.popViewController(animated: true)
  }
  
  func navigateToNextPageAfterSignUp() {
      viewController.performSegue(withIdentifier: "ShowPageAfterSignUp", sender: viewController)
  }
  
  // MARK: - Communication
  
  func passDataToNextScene(segue: UIStoryboardSegue) {
    // NOTE: Teach the router which scenes it can communicate with
    
    if segue.identifier == "ShowSomewhereScene" {
      passDataToSomewhereScene(segue: segue)
    }
  }
  
  func passDataToSomewhereScene(segue: UIStoryboardSegue) {
    // NOTE: Teach the router how to pass data to the next scene
    
    // let someWhereViewController = segue.destinationViewController as! SomeWhereViewController
    // someWhereViewController.output.name = viewController.output.name
  }
}
