//
//  ScheduleListConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ScheduleListViewController: ScheduleListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ScheduleListInteractor: ScheduleListViewControllerOutput
{
}

extension ScheduleListPresenter: ScheduleListInteractorOutput
{
}

class ScheduleListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ScheduleListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ScheduleListViewController)
  {
    let router = ScheduleListRouter()
    router.viewController = viewController
    
    let presenter = ScheduleListPresenter()
    presenter.output = viewController
    
    let interactor = ScheduleListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
