//
//  ScheduleListViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleListViewControllerInput {
  func displaySomething(viewModel: ScheduleList.Something.ViewModel)
}

protocol ScheduleListViewControllerOutput {
  func doSomething(request: ScheduleList.Something.Request)
}

class ScheduleListViewController: UIViewController, ScheduleListViewControllerInput {
  var output: ScheduleListViewControllerOutput!
  var router: ScheduleListRouter!
  
  @IBOutlet weak var tableView: UITableView!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib() {
    super.awakeFromNib()
    ScheduleListConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }
  
  // MARK: - Event handling
  
  @IBAction func addNewMedicine(_ sender: Any) {
    
  }
  
  // MARK: - Display logic
  
  func displaySomething(viewModel: ScheduleList.Something.ViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
