//
//  AddPatientPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddPatientPresenterInput {
  func presentErrorMessage(response: AddPatient.Response)
  func presentListScreen()
}

protocol AddPatientPresenterOutput: class {
  func displayErrorMessage(viewModel: AddPatient.ViewModel)
  func displayListScreen()
}

class AddPatientPresenter: AddPatientPresenterInput {
  weak var output: AddPatientPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentErrorMessage(response: AddPatient.Response) {
    let viewModel = AddPatient.ViewModel(message: response.resultMessage)
    output.displayErrorMessage(viewModel: viewModel)
  }
  
  func presentListScreen() {
    output.displayListScreen()
  }
}
