//
//  AddPatientConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension AddPatientViewController: AddPatientPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension AddPatientInteractor: AddPatientViewControllerOutput
{
}

extension AddPatientPresenter: AddPatientInteractorOutput
{
}

class AddPatientConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = AddPatientConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: AddPatientViewController)
  {
    let router = AddPatientRouter()
    router.viewController = viewController
    
    let presenter = AddPatientPresenter()
    presenter.output = viewController
    
    let interactor = AddPatientInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
