//
//  AddPatientInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AddPatientInteractorInput {
  func addNewPatient(request: AddPatient.Request)
}

protocol AddPatientInteractorOutput {
  func presentErrorMessage(response: AddPatient.Response)
  func presentListScreen()
}

class AddPatientInteractor: AddPatientInteractorInput {
  var output: AddPatientInteractorOutput!
  var worker: AddPatientWorker!
  
  // MARK: - Business logic
  
  func addNewPatient(request: AddPatient.Request) {
    // NOTE: Create some Worker to do the work
    
    worker = AddPatientWorker()
    worker.addPatient(request: request) { (result, message) in
      if result {
        self.output.presentListScreen()
      }
      else {
        let response = AddPatient.Response(result: false, resultMessage: message)
        self.output.presentErrorMessage(response: response)
      }
    }
    
    // NOTE: Pass the result to the Presenter
    
  }
}
