//
//  ScheduleDetailsConfigurator.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ScheduleDetailsViewController: ScheduleDetailsPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension ScheduleDetailsInteractor: ScheduleDetailsViewControllerOutput
{
}

extension ScheduleDetailsPresenter: ScheduleDetailsInteractorOutput
{
}

class ScheduleDetailsConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = ScheduleDetailsConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: ScheduleDetailsViewController)
  {
    let router = ScheduleDetailsRouter()
    router.viewController = viewController
    
    let presenter = ScheduleDetailsPresenter()
    presenter.output = viewController
    
    let interactor = ScheduleDetailsInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
