//
//  ScheduleDetailsInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleDetailsInteractorInput
{
  func doSomething(request: ScheduleDetails.Something.Request)
}

protocol ScheduleDetailsInteractorOutput
{
  func presentSomething(response: ScheduleDetails.Something.Response)
}

class ScheduleDetailsInteractor: ScheduleDetailsInteractorInput
{
  var output: ScheduleDetailsInteractorOutput!
  var worker: ScheduleDetailsWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: ScheduleDetails.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = ScheduleDetailsWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = ScheduleDetails.Something.Response()
    output.presentSomething(response: response)
  }
}
