//
//  ScheduleDetailsViewController.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleDetailsViewControllerInput
{
  func displaySomething(viewModel: ScheduleDetails.Something.ViewModel)
}

protocol ScheduleDetailsViewControllerOutput
{
  func doSomething(request: ScheduleDetails.Something.Request)
}

class ScheduleDetailsViewController: UIViewController, ScheduleDetailsViewControllerInput
{
  var output: ScheduleDetailsViewControllerOutput!
  var router: ScheduleDetailsRouter!
  
  // MARK: - Object lifecycle
  
  override func awakeFromNib()
  {
    super.awakeFromNib()
    ScheduleDetailsConfigurator.sharedInstance.configure(viewController: self)
  }
  
  // MARK: - View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomethingOnLoad()
  }
  
  // MARK: - Event handling
  
  func doSomethingOnLoad()
  {
    // NOTE: Ask the Interactor to do some work
    
    let request = ScheduleDetails.Something.Request()
    output.doSomething(request: request)
  }
  
  // MARK: - Display logic
  
  func displaySomething(viewModel: ScheduleDetails.Something.ViewModel)
  {
    // NOTE: Display the result from the Presenter
    
    // nameTextField.text = viewModel.name
  }
}
