//
//  ScheduleDetailsPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ScheduleDetailsPresenterInput
{
  func presentSomething(response: ScheduleDetails.Something.Response)
}

protocol ScheduleDetailsPresenterOutput: class
{
  func displaySomething(viewModel: ScheduleDetails.Something.ViewModel)
}

class ScheduleDetailsPresenter: ScheduleDetailsPresenterInput
{
  weak var output: ScheduleDetailsPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: ScheduleDetails.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = ScheduleDetails.Something.ViewModel()
    output.displaySomething(viewModel: viewModel)
  }
}
