//
//  MedicinesListInteractor.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MedicinesListInteractorInput {
  func loadAllMedicines()
}

protocol MedicinesListInteractorOutput {
  func presentAllItems(response: MedicinesList.Response)
}

class MedicinesListInteractor: MedicinesListInteractorInput {
  var output: MedicinesListInteractorOutput!
  
  // MARK: - Business logic
  
  func loadAllMedicines() {
    let worker = MedicinesListWorker()
    
    worker.loadAllMedicines { (items) in
      let response = MedicinesList.Response(items: items)
      self.output.presentAllItems(response: response)
    }
  }

}
