//
//  MedicinesListWorker.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import Foundation
import CoreData


typealias MedicinesListWorkerCompletion = (_ items:[MedicinesList.MedicineShowItem]) -> Void

class MedicinesListWorker {
  // MARK: - Business Logic
  
  func loadAllMedicines(completion:@escaping MedicinesListWorkerCompletion) {
    CoreDataManager.shared.performForegroundTask { (context) in
      let request:NSFetchRequest<ManagedMedicine> = ManagedMedicine.fetchRequest()
    
      do {
        let medicines = try context.fetch(request)
        
        completion(self.convertManagedObjectToShowObjects(items: medicines))
      }
      catch {
        completion([])
      }
      
      
    }
  }
}

private extension MedicinesListWorker {
  func convertManagedObjectToShowObjects(items:[ManagedMedicine]) -> [MedicinesList.MedicineShowItem] {
    
    return items.map({ (managedMedicine) -> MedicinesList.MedicineShowItem in
      return convertManagedObjectToShowObjct(managedMedicine: managedMedicine)
    })
  }
  
  func convertManagedObjectToShowObjct(managedMedicine:ManagedMedicine) -> MedicinesList.MedicineShowItem {
    return MedicinesList.MedicineShowItem(name: managedMedicine.name ?? "")
  }
}
