//
//  MedicinesListPresenter.swift
//  NurseHelper
//
//  Created by Vyacheslav Okulov on 2/2/17.
//  Copyright (c) 2017 Vyacheslav Okulov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MedicinesListPresenterInput {
  func presentAllItems(response: MedicinesList.Response)
}

protocol MedicinesListPresenterOutput: class {
  func displayAllItems(viewModel: MedicinesList.ViewModel)
}

class MedicinesListPresenter: MedicinesListPresenterInput {
  weak var output: MedicinesListPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentAllItems(response: MedicinesList.Response) {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    let viewModel = MedicinesList.ViewModel(items: response.items)
    output.displayAllItems(viewModel: viewModel)
  }
}
